Add Option to use Anon HTTPS URIs instead of SSH
Justintime50/github-archive pull request #35
Opened 2021-09-13 17:56 UTC by danieldjewell

Without this option, the only URL used to clone a repo was the SSH URL.
This adds a simple flag to switch clone operations to using the HTTPS
URL. The default behavior of using SSH is preserved so as to not break
scripts, etc.

Tested and seems to work just fine. 

I tried to follow the conventions already established -- I suppose one improvement would be to move the new arg higher in the parser list....

2021-09-13 18:48 UTC, Justintime50 commented
Thank you for the PR!

Let me think on this, we could probably do something along these lines, I'd want to ensure we don't break stuff with mixed content such as some SSH and some HTML.

Can you for now add trailing commas where possible? The code looks sound, will look it over again shortly to see if there are any edge cases we can protect against.

2021-09-13 18:52 UTC, Justintime50 requested changes

2021-09-13 18:52 UTC, Justintime50 commented on github_archive/archive.py
> +        use_https=False
Let's add a trailing comma here

2021-09-13 18:52 UTC, Justintime50 commented on github_archive/cli.py
> +            use_https=self.https
Trailing comma

2021-09-13 18:52 UTC, Justintime50 commented on github_archive/cli.py
> +            help='Use HTTPS URLs instead of SSH.'
Trialing comma

2021-09-13 23:18 UTC, Justintime50 commented
For future travelers, here is some context as to why supporting both may be advantageous: https://stackoverflow.com/questions/11041729/why-does-github-recommend-https-over-ssh

2021-09-15 00:29 UTC, danieldjewell commented
> For future travelers, here is some context as to why supporting both may be advantageous: https://stackoverflow.com/questions/11041729/why-does-github-recommend-https-over-ssh

That's a cool article -- and good guidance. 

I personally always use HTTPS if cloning anything public (it also at least *seems* faster... but I haven't measured it - human perception of time is still in alpha stage :grin: ) ... I wasn't even aware that authenticated HTTPS access was possible.... (For my repos I clone using SSH + keys -- once configured, it's easier for managing pushes.)

Will take a look at the comments and see what I can do - thanks for taking the time to look it over!

2021-09-15 00:46 UTC, danieldjewell commented
Yep, I'd be happy to fix those. (I've never been huge on trailing commas personally, but I can see their utility... sorry for not picking up on that originally.)

I never even realized that the topic is mentioned in PEP-8: https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas

In reading about this I discovered that `flake8` actually doesn't report the lack of trailing commas by default... but there's a plugin for that! (I ran flake8 before I submitted the PR since that's what was configured as the linter... and was a little surprised when you commented about it and flake8 didn't warn me...)

Here's the plugin... https://github.com/PyCQA/flake8-commas

(I tried it and sure enough, it lints the lack of trailing commas... Adding it to the project should be as simple as adding it to the venv...)

Related side note: Have you thought about possibly selecting a code formatter? (Black, yapf, your pick) Would be really nice from a newcomer's perspective to be able to do a `make format` or something and know that things are consistent. (I try my best to be consistent with the project but I'm human and sometimes miss things :))

2021-09-15 00:52 UTC, danieldjewell commented
Changed. See https://github.com/Justintime50/github-archive/pull/35/commits/8b3646049cfe8b0f9744cd44965232a0cda77cad

2021-09-15 06:23 UTC, Justintime50 approved these changes
Thanks for adding those trailing commas! That will help keep future diffs small since someone won't need to add them in when the list grows.

I'll take one more look in the next couple days and plan to get this released shortly.

2021-09-16 01:29 UTC, merged

2021-09-19 05:32 UTC, Justintime50 commented
Keep an eye on https://github.com/Justintime50/github-archive/pull/37 as that will be when I release the next version which contains this fix. I'm going to wait a day or two because Coveralls is being weird and I want a clean build at release time.